[project]
name = "comp0016-website-report-team-25"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.7.5",
    "mkdocs-video>=1.5.0",
    "mkdocstrings>=1.0.3",
    "pymdown-extensions>=10.21",
]
